// Generated by https://quicktype.io

import { type User } from './user.interface';

export interface LoginResponse {
  user: User;
  access_token: string;
}

export interface Login {
  email: string;
  password: string;
}
